baseurl = "https://example.org/"
languageCode = "en-us"
title = "BoxUp Crime"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

    # Custom css
    custom_css = ["css/styles.css"]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "BoxUp Crime"
   	description = "BoxUpCrime is a social youth organisation operating out of the London borough Barking and Dagenham. We work with young people at risk of having their lives ruined by crime and motivate them to rebuild and recapture their dreams and aspirations."


	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "img/logo-small2.png"

		[params.navigation.links]
			about        = "About Us"
            mission      = "Our Mission"
            location     = "Location"
            achievements = "Achievements"
            blog         = "Blog"
            contact      = "Contact Us"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Rebuilding Misguided Dreams"
        subtitle   = "Founded in 2013, BoxUpCrime is now London's leading social youth organisation. We have helped thousands of young people throughout London from disadvantaged and troubled backgrounds to reclaim their dreams."
        buttonText = "Find out more"


	# About section
	[params.about]
	    headline    = "Who We Are"
        description = "BoxUpCrime is a social youth organisation operating out of the London borough Barking and Dagenham. We work with young people at risk of having their lives ruined by crime and motivate them to rebuild and recapture their dreams and aspirations. We believe that every young person is entitled to a bright future, inspired by their hopes and dreams, regardless of their background. We deliver our tailored sessions to schools, pupil referral units and community centres across London. In our weekly sessions, we offer a foundation of discipline through engaging boxing training, educational programmes and mentoring. We provide young people job opportunities and apprenticeships as a stepping stone to their future."
        buttonText  = "Our Founder"

	# Mission section
    [params.mission]
        headline    = "Our Mission"
        description = "We want to provide the opportunity and resources to help all young people discover a true sense of self identity as well as guiding them to develop self-motivation. These skills will allow them to go on to live fulfiling and successful lives, which will ultimately decrease and prevent their involvement in crime."
        buttonText  = "Work With Us"

	# Statistics section
    [params.achievements]
        headline    = "Achievements and Awards"

    # Location section
    [params.locations]
        headline = "Our Locations"
        description = "Please select one of our locations below:"
        location1 = "BoxUp UK"
        location2 = "BoxUp Switzerland"
        location3 = "BoxUp Ghana"

        # Portfolio modals
    	[params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttonText = "Close"

        # Blog section
    	[params.blog]
    	    headline = "Let's Get In Touch!"
    	    description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
    	    phone = "123-456-6789"
    	    email = "feedback@startbootstrap.com"

    	# Contact section
    	[params.contact]
    	    headline = "Contact Us"
    	    phone = "0208 517 4446"
    	    email = "info@boxupcrime.org"
    	    address = "59 Grosvenor Road, Dagenham, Essex, RM8 1NL"
    	    openingTimes1 = "Monday: 09:00 - 17:00"
    	    openingTimes2 = "Tuesday: 09:00 - 17:00"
    	    openingTimes3 = "Wednesday: 09:00 - 17:00"
    	    openingTimes4 = "Thursday: 09:00 - 17:00"
    	    openingTimes5 = "Friday 09:00 - 17:00"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
